version: "3"
services:
  redis:
    image: redis:latest
    restart: "no"
    container_name: redis-site
    environment:
      - REDIS_PASSWORD
    ports:
      - 6379:6379
    volumes:
      - /usr/site/conf/redis.conf:/etc/redis/redis.conf
      - /usr/site/data/redis:/data
    command: redis-server /etc/redis/redis.conf --requirepass werido
    # command: redis-server --requirepass werido
    privileged: true

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
      - 61613:61613
    environment:
      - RABBITMQ_DEFAULT_USER=werido  # 账号
      - RABBITMQ_DEFAULT_PASS=359066432  # 密码
      - RABBITMQ_ERLANG_COOKIE=weridolin
    # volumes:
    #  - /usr/rabbitmq:/etc/rabbitmq/enabled_plugins
