version: '3'
services:
  servers:
    build: 
      context: ../
      dockerfile: ./dev/Dockerfile
    command:       
      - /bin/bash
      - -c
      - |
        echo 'start server...'
        go install github.com/cortesi/modd/cmd/modd
        modd -f modd-linux.conf
    # volumes:
    #   - /pythons/blogNew/werido-site-backend/:/var/www/html/weridoBlog/
    ports:
      - "10080:8080"
      - "10081:8081"
      - "10082:8082"
      - "4008:4008"
    networks:
      - simple_notifications

networks:
  simple_notifications:
    driver: bridge
    external:
      name: simple_notifications