// Code generated by goctl. DO NOT EDIT.
package types

type UserInfo struct {
	Username     string   `json:"username"`
	Email        string   `json:"email"`
	Phone        string   `json:"phone"`
	Avatar       string   `json:"avatar"`
	Role         []string `json:"role"`
	IsSuperAdmin bool     `json:"is_super_admin"`
	Age          int      `json:"age"`
	Gender       int8     `json:"gender"`
}

type UserInfoWithToken struct {
	UserInfo
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refresh_token"`
}

type RegisterReq struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Username string `json:"username"`
}

type RegisterResp struct {
	BaseResponse
	Data UserInfo `json:"data"`
}

type LoginReq struct {
	Count    string `json:"count"`
	Password string `json:"password"`
}

type LoginResp struct {
	BaseResponse
	Data UserInfoWithToken `json:"data"`
}

type LogoutResp struct {
	BaseResponse
}

type UpdateUserInfoResp struct {
	BaseResponse
	Data UserInfo `json:"data"`
}

type BaseResponse struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	// Data interface{} `json:"data"`
}
