emailConsumerConfig:
  sender: ${DEFAULT_SENDER}
  pwd: ${DEFAULT_PWD}
  interval: 1

rabbitmqConfig:
  rabbitmqUri: ${RABBITMQ_URI}
  emailMessageQueueName: "consumer.email.nofify.queue"


  #监控
Prometheus:
  Host: 0.0.0.0
  Port: 4003
  Path: /metrics